# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waktusolat < Formula
  desc "Waktu Solat CLI"
  homepage "https://github.com/waktusolatmy/cli"
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/waktusolatmy/cli/releases/download/v0.0.5/waktusolat-0.0.5-darwin-amd64.tar.gz"
      sha256 "d2cc9a31900685fa646d0dd3ffd9ed8ae6dd6b108d5a1aafa567330afca5d8e7"

      def install
        bin.install "waktusolat"
      end
    end
    on_arm do
      url "https://github.com/waktusolatmy/cli/releases/download/v0.0.5/waktusolat-0.0.5-darwin-arm64.tar.gz"
      sha256 "bcbecb8202975e5102af6e9c04298e4c4372f44f8ecce1b376d9271cfda5506d"

      def install
        bin.install "waktusolat"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waktusolatmy/cli/releases/download/v0.0.5/waktusolat-0.0.5-linux-amd64.tar.gz"
        sha256 "4a3d127d2fad21679b5f9677610f08a0770db3506570f7dabf8f7f71ea626e59"

        def install
          bin.install "waktusolat"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/waktusolatmy/cli/releases/download/v0.0.5/waktusolat-0.0.5-linux-arm.tar.gz"
        sha256 "515faf0ad82e84c7d9f0f5009da0f2f7164c79802b948ea333b14be1534548fa"

        def install
          bin.install "waktusolat"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/waktusolatmy/cli/releases/download/v0.0.5/waktusolat-0.0.5-linux-arm64.tar.gz"
        sha256 "ae2ef94e411cb130ae70570065542f1a75699d33d37e1392a015e3d3b6456cea"

        def install
          bin.install "waktusolat"
        end
      end
    end
  end
end
